'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Icon } from '@/components/workspace/icons';
import { formatIdr, getJobCandidates, jobInitials, countStage, stageClass } from '@/components/workspace/format';
import { JobFormModal } from '@/components/workspace/modals';
import { useWorkspace } from '@/components/workspace/workspace-provider';
import { PIPELINE_STAGES } from '@/types/ats';

export function JobOverviewPage({ jobId }: { jobId: string }) {
  const { getJob, candidates } = useWorkspace();
  const [editing, setEditing] = useState(false);
  const job = getJob(jobId);
  if (!job) return <div className="content"><div className="empty-state"><div><h3>Job not found</h3><p>This job may have been removed or is still loading.</p><Link className="button button-secondary" href="/jobs">Back to jobs</Link></div></div></div>;
  const jobCandidates = getJobCandidates(candidates, job.id);
  return <div className="content"><JobHeader jobId={job.id} jobTitle={job.title} department={job.department} location={job.location} arrangement={job.arrangement} status={job.status} /><div className="grid-two"><section className="panel"><div className="panel-header"><h2>About this role</h2><button className="panel-link" onClick={() => setEditing(true)}>Edit details</button></div><div style={{ padding: 21 }}><p style={{ color: 'var(--muted)', fontSize: 14, lineHeight: 1.7, marginBottom: 20 }}>{job.description}</p><div className="drawer-grid"><Detail label="Salary range" value={`${formatIdr(job.salary[0])} – ${formatIdr(job.salary[1])} / month`} /><Detail label="Hiring manager" value={job.manager} /><Detail label="Employment type" value={job.type} /><Detail label="Target hire date" value={job.target} /></div></div></section><section className="panel"><div className="panel-header"><h2>Pipeline snapshot</h2><Link className="panel-link" href={`/jobs/${job.id}/pipeline`}>Open board</Link></div><div className="activity-list">{PIPELINE_STAGES.map((stage) => <div className="activity-row" key={stage}><span className={`stage-badge stage-${stageClass(stage)}`}>{countStage(candidates, job.id, stage)}</span><div className="activity-copy"><strong>{stage}</strong><p>{countStage(candidates, job.id, stage) === 1 ? 'candidate' : 'candidates'} in this stage</p></div></div>)}</div></section></div><section className="panel section-gap"><div className="panel-header"><h2>Recent candidates</h2><Link className="panel-link" href={`/jobs/${job.id}/candidates`}>View candidates</Link></div>{jobCandidates.length ? <CandidateTable candidates={jobCandidates} jobId={job.id} /> : <div className="empty-state"><div><div className="empty-icon" style={{ margin: '0 auto 12px' }}><Icon name="users" size={19} /></div><h3>No candidates yet</h3><p>Upload your first CV to start building this pipeline.</p><Link className="button button-secondary" href={`/jobs/${job.id}/candidates`}>Open candidates</Link></div></div>}</section>{editing && <JobFormModal job={job} onClose={() => setEditing(false)} />}</div>;
}

export function JobHeader({ jobId, jobTitle, department, location, arrangement, status, active = 'overview' }: { jobId: string; jobTitle: string; department: string; location: string; arrangement: string; status: string; active?: 'overview' | 'candidates' | 'pipeline' | 'settings' }) { return <div className="job-context"><div className="context-top"><div className="context-heading"><span className="context-mark">{jobInitials(jobTitle)}</span><div><div className="eyebrow">Active job</div><h1>{jobTitle}</h1><p className="context-sub">{department} · {location} · {arrangement} · <span className={`status-badge ${status === 'Open' ? 'status-open' : 'status-paused'}`}><i className="dot" />{status}</span></p></div></div><div className="header-actions"><Link className="button button-secondary" href={`/jobs/${jobId}/settings`}>Job settings</Link><Link className="button button-primary" href={`/jobs/${jobId}/candidates`}><Icon name="users" size={16} /> Candidates</Link></div></div><div className="context-tabs"><Link className={`context-tab ${active === 'overview' ? 'active' : ''}`} href={`/jobs/${jobId}`}>Overview</Link><Link className={`context-tab ${active === 'candidates' ? 'active' : ''}`} href={`/jobs/${jobId}/candidates`}>Candidates</Link><Link className={`context-tab ${active === 'pipeline' ? 'active' : ''}`} href={`/jobs/${jobId}/pipeline`}>Pipeline</Link><Link className={`context-tab ${active === 'settings' ? 'active' : ''}`} href={`/jobs/${jobId}/settings`}>Job settings</Link></div></div>; }

function Detail({ label, value }: { label: string; value: string }) { return <div><span className="detail-label">{label}</span><span className="detail-value">{value}</span></div>; }

function CandidateTable({ candidates, jobId }: { candidates: import('@/types/ats').Candidate[]; jobId: string }) { return <div className="candidate-table-wrap"><table className="candidate-table"><thead><tr><th>Candidate</th><th>Current role</th><th>Location</th><th>Stage</th><th>Source</th><th>Added</th></tr></thead><tbody>{candidates.map((candidate) => { const application = candidate.applications[jobId]; return <tr key={candidate.id}><td><Link className="candidate-cell" href={`/candidates/${candidate.id}`}><span className="candidate-avatar">{candidate.initials}</span><span><strong>{candidate.name}</strong><span>{candidate.email}</span></span></Link></td><td>{candidate.currentRole}</td><td>{candidate.location}</td><td><span className={`stage-badge stage-${stageClass(application.stage)}`}>{PIPELINE_STAGES.find((stage) => stageClass(stage) === application.stage) || application.stage}</span></td><td>{application.source}</td><td>{application.added.replace(', 2026', '')}</td></tr>; })}</tbody></table></div>; }
