'use client';

import { useState } from 'react';
import { Icon } from '@/components/workspace/icons';
import { PIPELINE_STAGES } from '@/types/ats';

export function SettingsPage() {
  const [tab, setTab] = useState<'pipeline' | 'tags' | 'workspace'>('pipeline');
  return <div className="content"><div className="page-header"><div><p className="eyebrow">Workspace / preferences</p><h1>Settings</h1><p className="page-description">Keep the workspace language and defaults consistent for the team.</p></div></div><div className="settings-layout"><nav className="settings-nav" aria-label="Settings navigation">{[['pipeline','Pipeline stages'],['tags','Tags'],['workspace','Workspace']].map(([key,label]) => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key as typeof tab)} key={key}>{label}</button>)}</nav><section className="panel">{tab === 'pipeline' ? <PipelineSettings /> : tab === 'tags' ? <TagSettings /> : <WorkspaceSettings />}</section></div></div>;
}

function PipelineSettings() { return <div className="settings-panel"><h2>Pipeline stages</h2><p className="settings-intro">These stages are used for every new job. You can still move a candidate between stages at any time.</p><div className="pipeline-list">{PIPELINE_STAGES.map((stage, index) => <div className="pipeline-item" key={stage}><span className="drag-handle"><Icon name="drag" size={16} /></span><span className="stage-color" style={{ background: ['#7888e2','#5fb194','#dfaa62','#9e80d4','#43a777','#d58e98'][index] }} /><span>{stage}</span><small>{index === 0 ? 'Default entry stage' : index === PIPELINE_STAGES.length - 1 ? 'Closed stage' : 'Active'}</small><button className="icon-button" aria-label={`Edit ${stage}`}><Icon name="more" size={16} /></button></div>)}</div><div className="header-actions" style={{ justifyContent: 'flex-start', marginTop: 17 }}><button className="button button-secondary"><Icon name="plus" size={15} /> Add stage</button></div></div>; }
function TagSettings() { const tags = ['High priority', 'Referral', 'Needs portfolio', 'Strong fit', 'Follow up', 'Remote-ready']; return <div className="settings-panel"><h2>Candidate tags</h2><p className="settings-intro">Use tags to add lightweight context without changing a candidate’s pipeline stage.</p><div className="skill-list">{tags.map((tag) => <span className="tag" style={{ fontSize: 12, padding: '8px 10px' }} key={tag}>{tag}</span>)}</div><div className="settings-divider" /><div className="field" style={{ maxWidth: 350 }}><label htmlFor="new-tag">Add a tag</label><div style={{ display: 'flex', gap: 8 }}><input id="new-tag" className="text-input" placeholder="e.g. Needs reference check" /><button className="button button-primary">Add tag</button></div></div></div>; }
function WorkspaceSettings() { return <div className="settings-panel"><h2>Workspace settings</h2><p className="settings-intro">A few basics for the recruiting workspace.</p><div className="settings-form"><div className="field"><label htmlFor="workspace-name">Workspace name</label><input className="text-input" id="workspace-name" defaultValue="Harbor Works" /></div><div className="field-grid"><div className="field"><label htmlFor="default-location">Default location</label><input className="text-input" id="default-location" defaultValue="Jakarta" /></div><div className="field"><label htmlFor="currency">Currency</label><select className="select-input" id="currency"><option>Indonesian Rupiah (Rp)</option></select></div></div><div className="settings-divider" /><button className="button button-primary" style={{ width: 'max-content' }}>Save changes</button></div></div>; }
