import { Candidate, Job } from '@/types/ats';

export const demoJobs: Job[] = [
  { id: 'job-1', title: 'Senior Product Designer', department: 'Product & Design', location: 'Jakarta', arrangement: 'Hybrid', type: 'Full-time', manager: 'Maya Chen', status: 'Open', salary: [18000000, 26000000], created: 'Aug 28, 2026', target: 'Oct 18, 2026', description: 'Shape the next generation of tools for modern recruiting teams.' },
  { id: 'job-2', title: 'Customer Success Lead', department: 'Customer Experience', location: 'Jakarta', arrangement: 'Remote', type: 'Full-time', manager: 'Arif Nugraha', status: 'Open', salary: [15000000, 22000000], created: 'Sep 02, 2026', target: 'Oct 04, 2026', description: 'Build a thoughtful, high-touch customer experience as we scale.' },
  { id: 'job-3', title: 'Frontend Engineer', department: 'Engineering', location: 'Bandung', arrangement: 'Hybrid', type: 'Full-time', manager: 'Dimas Putra', status: 'Open', salary: [20000000, 32000000], created: 'Sep 07, 2026', target: 'Nov 01, 2026', description: 'Turn complex workflow ideas into fast, accessible product experiences.' },
  { id: 'job-4', title: 'People Operations Associate', department: 'People', location: 'Jakarta', arrangement: 'On-site', type: 'Full-time', manager: 'Maya Chen', status: 'Paused', salary: [10000000, 14000000], created: 'Jul 19, 2026', target: '—', description: 'Help create a smooth, human experience for every person at the company.' },
];

export const demoCandidates: Candidate[] = [
  { id: 'candidate-1', name: 'Nadia Wijaya', initials: 'NW', currentRole: 'Product Designer', location: 'Jakarta', email: 'nadia.wijaya@email.com', phone: '+62 812 4400 1288', whatsapp: '6281244001288', summary: 'Product designer with a strong track record turning research into clear, useful workflows for B2B products.', skills: ['Product design', 'Figma', 'Research', 'Prototyping'], experience: 6, desiredTitle: 'Senior Product Designer', salary: 22000000, availability: '30 days', linkedin: 'linkedin.com/in/nadiawijaya', portfolio: 'nadiawijaya.design', cvName: 'Nadia_Wijaya_CV.pdf', education: 'B.Des. Visual Communication Design · BINUS University', certifications: ['Google UX Design Certificate'], employment: [{ company: 'KitaWorks', title: 'Product Designer', dates: '2021 — Present' }, { company: 'Bumi Digital', title: 'UX Designer', dates: '2019 — 2021' }], applications: { 'job-1': { candidateId: 'candidate-1', jobId: 'job-1', stage: 'shortlist', source: 'LinkedIn', added: 'Sep 15, 2026', needsReview: false, notes: 'Strong portfolio. Ask about design systems experience.' }, 'job-2': { candidateId: 'candidate-1', jobId: 'job-2', stage: 'new', source: 'Referral', added: 'Sep 15, 2026', needsReview: false, notes: '' } } },
  { id: 'candidate-2', name: 'Rizky Pranata', initials: 'RP', currentRole: 'UX Researcher', location: 'Jakarta', email: 'rizky.pranata@email.com', phone: '+62 813 7021 6642', whatsapp: '6281370216642', summary: 'Researcher who brings structure to ambiguous problems and turns customer insight into product direction.', skills: ['User research', 'Service design', 'Analytics'], experience: 4, desiredTitle: 'Senior Product Designer', salary: 19000000, availability: 'Immediate', linkedin: 'linkedin.com/in/rizkypranata', portfolio: 'rizkyresearch.com', cvName: 'Rizky_Pranata_CV.pdf', education: 'M.Sc. Human Computer Interaction · University of Indonesia', certifications: [], employment: [{ company: 'Saku Labs', title: 'UX Researcher', dates: '2022 — Present' }, { company: 'Cakap', title: 'Research Associate', dates: '2020 — 2022' }], applications: { 'job-1': { candidateId: 'candidate-2', jobId: 'job-1', stage: 'interview', source: 'Job board', added: 'Sep 12, 2026', needsReview: true, notes: 'Phone number was found in the CV. Confirm preferred WhatsApp number.' } } },
  { id: 'candidate-3', name: 'Clara Santoso', initials: 'CS', currentRole: 'Brand Designer', location: 'Bandung', email: 'clara.santoso@email.com', phone: '+62 811 3550 9012', whatsapp: '6281135509012', summary: 'Brand and visual designer with a warm, systems-minded approach to creating cohesive product stories.', skills: ['Brand systems', 'Visual design', 'Illustration'], experience: 5, desiredTitle: 'Senior Product Designer', salary: 20500000, availability: '60 days', linkedin: 'linkedin.com/in/clarasantoso', portfolio: 'clarasantoso.studio', cvName: 'Clara_Santoso_CV.pdf', education: 'B.A. Communication Design · Telkom University', certifications: ['Adobe Certified Professional'], employment: [{ company: 'Ruang Cerita', title: 'Brand Designer', dates: '2020 — Present' }, { company: 'Studio Kecil', title: 'Visual Designer', dates: '2018 — 2020' }], applications: { 'job-1': { candidateId: 'candidate-3', jobId: 'job-1', stage: 'new', source: 'Portfolio submission', added: 'Sep 17, 2026', needsReview: false, notes: '' } } },
  { id: 'candidate-4', name: 'Fajar Aditya', initials: 'FA', currentRole: 'Customer Success Manager', location: 'Jakarta', email: 'fajar.aditya@email.com', phone: '+62 852 1129 7810', whatsapp: '6285211297810', summary: 'Customer success leader with experience growing retention and building scalable onboarding programs.', skills: ['Account management', 'Onboarding', 'Retention'], experience: 7, desiredTitle: 'Customer Success Lead', salary: 18500000, availability: '30 days', linkedin: 'linkedin.com/in/fajaraditya', portfolio: '', cvName: 'Fajar_Aditya_CV.pdf', education: 'B.A. Business Administration · Prasetiya Mulya University', certifications: ['Gainsight Customer Success'], employment: [{ company: 'Flowline', title: 'Customer Success Manager', dates: '2021 — Present' }, { company: 'Mekari', title: 'Customer Success Specialist', dates: '2018 — 2021' }], applications: { 'job-2': { candidateId: 'candidate-4', jobId: 'job-2', stage: 'shortlist', source: 'Referral', added: 'Sep 14, 2026', needsReview: false, notes: 'Referred by Sinta in Sales.' } } },
  { id: 'candidate-5', name: 'Salsabila Putri', initials: 'SP', currentRole: 'Frontend Developer', location: 'Bandung', email: 'salsabila.putri@email.com', phone: '+62 822 2198 3327', whatsapp: '6282221983327', summary: 'Frontend developer focused on resilient interfaces, design systems, and accessible component architecture.', skills: ['React', 'TypeScript', 'Design systems'], experience: 5, desiredTitle: 'Frontend Engineer', salary: 26000000, availability: 'Immediate', linkedin: 'linkedin.com/in/salsabilaputri', portfolio: 'salsabila.dev', cvName: 'Salsabila_Putri_CV.pdf', education: 'B.Comp. Computer Science · Institut Teknologi Bandung', certifications: [], employment: [{ company: 'Kelana', title: 'Frontend Developer', dates: '2022 — Present' }, { company: 'Binar Academy', title: 'Software Engineer', dates: '2019 — 2022' }], applications: { 'job-3': { candidateId: 'candidate-5', jobId: 'job-3', stage: 'interview', source: 'GitHub', added: 'Sep 10, 2026', needsReview: false, notes: 'Excellent take-home exercise.' } } },
  { id: 'candidate-6', name: 'Andi Kurniawan', initials: 'AK', currentRole: 'Full-stack Engineer', location: 'Jakarta', email: 'andi.kurniawan@email.com', phone: '+62 857 0933 1109', whatsapp: '6285709331109', summary: 'Product-minded full-stack engineer who enjoys shipping quickly without losing sight of quality.', skills: ['JavaScript', 'Node.js', 'Postgres'], experience: 8, desiredTitle: 'Frontend Engineer', salary: 29000000, availability: '45 days', linkedin: 'linkedin.com/in/andikurniawan', portfolio: 'andik.dev', cvName: 'Andi_Kurniawan_CV.pdf', education: 'B.Sc. Information Systems · Universitas Brawijaya', certifications: [], employment: [{ company: 'Nusa Tech', title: 'Full-stack Engineer', dates: '2019 — Present' }, { company: 'Kreasi Digital', title: 'Software Engineer', dates: '2016 — 2019' }], applications: { 'job-3': { candidateId: 'candidate-6', jobId: 'job-3', stage: 'shortlist', source: 'Job board', added: 'Sep 13, 2026', needsReview: false, notes: '' } } },
];
